# Generated by Django 2.0.4 on 2018-04-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_question_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
